### ISSUE TITLE
Allow team name to be unique to tournament

### ISSUE THREAD

**Issue by natenolting** [paulbunyancommunications/gigazonegaming#9]
@castillo-n Can you look into this. We're running into this issue with returning teams.

When creating a new team the the creator should allow for a team to be created with a unique name just to the current tournament. If there's a team registering that their name already exists but not in the tournament selected then maybe allow the creation?

### Scenario

1. Team Foo Bar registers for one tournament with players
2. Team Foo Bar registers for another tournament with different players from 1

#### Creation:
![screenshot at may 31 08-47-07](https://cloud.githubusercontent.com/assets/8352600/26634969/db176294-45dd-11e7-8811-8c185c624984.png)

#### Validation error:
When team is submitted that already is in the db.
![screenshot at may 31 08-47-37](https://cloud.githubusercontent.com/assets/8352600/26634975/e032c1ec-45dd-11e7-9cbe-df4619477fd2.png)

**Comment by castillo-n** [comment]
Back and front end now are working. Checks are done for email addresses, summoner names, and now as well if the summoner names are real. All tests are done except for the ones for the summoner name check if real in the back end. (I will see if I find time while I am out for these tests and changes)
